/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppsSaboriaIndexRouteImport } from './routes/_authenticated/apps/saboria/index'
import { Route as AuthenticatedAppsSaboriaReceitasRouteImport } from './routes/_authenticated/apps/saboria/receitas'
import { Route as AuthenticatedAppsSaboriaPlannerRouteImport } from './routes/_authenticated/apps/saboria/planner'
import { Route as AuthenticatedAppsSaboriaOnboardingRouteImport } from './routes/_authenticated/apps/saboria/onboarding'
import { Route as AuthenticatedAppsSaboriaNutriRouteImport } from './routes/_authenticated/apps/saboria/nutri'
import { Route as AuthenticatedAppsSaboriaGeladeiraRouteImport } from './routes/_authenticated/apps/saboria/geladeira'
import { Route as AuthenticatedAppsSaboriaFotoRouteImport } from './routes/_authenticated/apps/saboria/foto'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppsSaboriaIndexRoute =
  AuthenticatedAppsSaboriaIndexRouteImport.update({
    id: '/apps/saboria/',
    path: '/apps/saboria/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsSaboriaReceitasRoute =
  AuthenticatedAppsSaboriaReceitasRouteImport.update({
    id: '/apps/saboria/receitas',
    path: '/apps/saboria/receitas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsSaboriaPlannerRoute =
  AuthenticatedAppsSaboriaPlannerRouteImport.update({
    id: '/apps/saboria/planner',
    path: '/apps/saboria/planner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsSaboriaOnboardingRoute =
  AuthenticatedAppsSaboriaOnboardingRouteImport.update({
    id: '/apps/saboria/onboarding',
    path: '/apps/saboria/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsSaboriaNutriRoute =
  AuthenticatedAppsSaboriaNutriRouteImport.update({
    id: '/apps/saboria/nutri',
    path: '/apps/saboria/nutri',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsSaboriaGeladeiraRoute =
  AuthenticatedAppsSaboriaGeladeiraRouteImport.update({
    id: '/apps/saboria/geladeira',
    path: '/apps/saboria/geladeira',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsSaboriaFotoRoute =
  AuthenticatedAppsSaboriaFotoRouteImport.update({
    id: '/apps/saboria/foto',
    path: '/apps/saboria/foto',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/apps/saboria/foto': typeof AuthenticatedAppsSaboriaFotoRoute
  '/apps/saboria/geladeira': typeof AuthenticatedAppsSaboriaGeladeiraRoute
  '/apps/saboria/nutri': typeof AuthenticatedAppsSaboriaNutriRoute
  '/apps/saboria/onboarding': typeof AuthenticatedAppsSaboriaOnboardingRoute
  '/apps/saboria/planner': typeof AuthenticatedAppsSaboriaPlannerRoute
  '/apps/saboria/receitas': typeof AuthenticatedAppsSaboriaReceitasRoute
  '/apps/saboria/': typeof AuthenticatedAppsSaboriaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/apps/saboria/foto': typeof AuthenticatedAppsSaboriaFotoRoute
  '/apps/saboria/geladeira': typeof AuthenticatedAppsSaboriaGeladeiraRoute
  '/apps/saboria/nutri': typeof AuthenticatedAppsSaboriaNutriRoute
  '/apps/saboria/onboarding': typeof AuthenticatedAppsSaboriaOnboardingRoute
  '/apps/saboria/planner': typeof AuthenticatedAppsSaboriaPlannerRoute
  '/apps/saboria/receitas': typeof AuthenticatedAppsSaboriaReceitasRoute
  '/apps/saboria': typeof AuthenticatedAppsSaboriaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/apps/saboria/foto': typeof AuthenticatedAppsSaboriaFotoRoute
  '/_authenticated/apps/saboria/geladeira': typeof AuthenticatedAppsSaboriaGeladeiraRoute
  '/_authenticated/apps/saboria/nutri': typeof AuthenticatedAppsSaboriaNutriRoute
  '/_authenticated/apps/saboria/onboarding': typeof AuthenticatedAppsSaboriaOnboardingRoute
  '/_authenticated/apps/saboria/planner': typeof AuthenticatedAppsSaboriaPlannerRoute
  '/_authenticated/apps/saboria/receitas': typeof AuthenticatedAppsSaboriaReceitasRoute
  '/_authenticated/apps/saboria/': typeof AuthenticatedAppsSaboriaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/apps/saboria/foto'
    | '/apps/saboria/geladeira'
    | '/apps/saboria/nutri'
    | '/apps/saboria/onboarding'
    | '/apps/saboria/planner'
    | '/apps/saboria/receitas'
    | '/apps/saboria/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/apps/saboria/foto'
    | '/apps/saboria/geladeira'
    | '/apps/saboria/nutri'
    | '/apps/saboria/onboarding'
    | '/apps/saboria/planner'
    | '/apps/saboria/receitas'
    | '/apps/saboria'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/apps/saboria/foto'
    | '/_authenticated/apps/saboria/geladeira'
    | '/_authenticated/apps/saboria/nutri'
    | '/_authenticated/apps/saboria/onboarding'
    | '/_authenticated/apps/saboria/planner'
    | '/_authenticated/apps/saboria/receitas'
    | '/_authenticated/apps/saboria/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/apps/saboria/': {
      id: '/_authenticated/apps/saboria/'
      path: '/apps/saboria'
      fullPath: '/apps/saboria/'
      preLoaderRoute: typeof AuthenticatedAppsSaboriaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/saboria/receitas': {
      id: '/_authenticated/apps/saboria/receitas'
      path: '/apps/saboria/receitas'
      fullPath: '/apps/saboria/receitas'
      preLoaderRoute: typeof AuthenticatedAppsSaboriaReceitasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/saboria/planner': {
      id: '/_authenticated/apps/saboria/planner'
      path: '/apps/saboria/planner'
      fullPath: '/apps/saboria/planner'
      preLoaderRoute: typeof AuthenticatedAppsSaboriaPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/saboria/onboarding': {
      id: '/_authenticated/apps/saboria/onboarding'
      path: '/apps/saboria/onboarding'
      fullPath: '/apps/saboria/onboarding'
      preLoaderRoute: typeof AuthenticatedAppsSaboriaOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/saboria/nutri': {
      id: '/_authenticated/apps/saboria/nutri'
      path: '/apps/saboria/nutri'
      fullPath: '/apps/saboria/nutri'
      preLoaderRoute: typeof AuthenticatedAppsSaboriaNutriRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/saboria/geladeira': {
      id: '/_authenticated/apps/saboria/geladeira'
      path: '/apps/saboria/geladeira'
      fullPath: '/apps/saboria/geladeira'
      preLoaderRoute: typeof AuthenticatedAppsSaboriaGeladeiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/saboria/foto': {
      id: '/_authenticated/apps/saboria/foto'
      path: '/apps/saboria/foto'
      fullPath: '/apps/saboria/foto'
      preLoaderRoute: typeof AuthenticatedAppsSaboriaFotoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppsSaboriaFotoRoute: typeof AuthenticatedAppsSaboriaFotoRoute
  AuthenticatedAppsSaboriaGeladeiraRoute: typeof AuthenticatedAppsSaboriaGeladeiraRoute
  AuthenticatedAppsSaboriaNutriRoute: typeof AuthenticatedAppsSaboriaNutriRoute
  AuthenticatedAppsSaboriaOnboardingRoute: typeof AuthenticatedAppsSaboriaOnboardingRoute
  AuthenticatedAppsSaboriaPlannerRoute: typeof AuthenticatedAppsSaboriaPlannerRoute
  AuthenticatedAppsSaboriaReceitasRoute: typeof AuthenticatedAppsSaboriaReceitasRoute
  AuthenticatedAppsSaboriaIndexRoute: typeof AuthenticatedAppsSaboriaIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppsSaboriaFotoRoute: AuthenticatedAppsSaboriaFotoRoute,
  AuthenticatedAppsSaboriaGeladeiraRoute:
    AuthenticatedAppsSaboriaGeladeiraRoute,
  AuthenticatedAppsSaboriaNutriRoute: AuthenticatedAppsSaboriaNutriRoute,
  AuthenticatedAppsSaboriaOnboardingRoute:
    AuthenticatedAppsSaboriaOnboardingRoute,
  AuthenticatedAppsSaboriaPlannerRoute: AuthenticatedAppsSaboriaPlannerRoute,
  AuthenticatedAppsSaboriaReceitasRoute: AuthenticatedAppsSaboriaReceitasRoute,
  AuthenticatedAppsSaboriaIndexRoute: AuthenticatedAppsSaboriaIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
