
-- PETS
CREATE TABLE public.pets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('dog','cat','other')),
  breed TEXT,
  birth_date DATE,
  gender TEXT CHECK (gender IN ('male','female','unknown')),
  weight NUMERIC(5,2),
  photo_url TEXT,
  microchip TEXT,
  neutered BOOLEAN DEFAULT false,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pets TO authenticated;
GRANT ALL ON public.pets TO service_role;
ALTER TABLE public.pets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Owners manage own pets" ON public.pets FOR ALL
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- HEALTH RECORDS
CREATE TABLE public.pet_health_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pet_id UUID NOT NULL REFERENCES public.pets(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  record_date DATE NOT NULL DEFAULT CURRENT_DATE,
  weight NUMERIC(5,2),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pet_health_records TO authenticated;
GRANT ALL ON public.pet_health_records TO service_role;
ALTER TABLE public.pet_health_records ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Owners manage own health records" ON public.pet_health_records FOR ALL
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- VACCINATIONS
CREATE TABLE public.pet_vaccinations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pet_id UUID NOT NULL REFERENCES public.pets(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  applied_on DATE NOT NULL,
  next_booster DATE,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pet_vaccinations TO authenticated;
GRANT ALL ON public.pet_vaccinations TO service_role;
ALTER TABLE public.pet_vaccinations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Owners manage own vaccinations" ON public.pet_vaccinations FOR ALL
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- MEALS
CREATE TABLE public.pet_meals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pet_id UUID NOT NULL REFERENCES public.pets(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  meal_date DATE NOT NULL DEFAULT CURRENT_DATE,
  meal_time TIME,
  type TEXT,
  amount TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pet_meals TO authenticated;
GRANT ALL ON public.pet_meals TO service_role;
ALTER TABLE public.pet_meals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Owners manage own meals" ON public.pet_meals FOR ALL
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- CHAT MESSAGES (vet chat, per pet)
CREATE TABLE public.pet_chat_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pet_id UUID NOT NULL REFERENCES public.pets(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('user','assistant','system')),
  content TEXT NOT NULL,
  urgency TEXT CHECK (urgency IN ('green','yellow','red')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pet_chat_messages TO authenticated;
GRANT ALL ON public.pet_chat_messages TO service_role;
ALTER TABLE public.pet_chat_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Owners manage own pet chat" ON public.pet_chat_messages FOR ALL
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- PLANS (food, training, health report generated by AI)
CREATE TABLE public.pet_plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pet_id UUID NOT NULL REFERENCES public.pets(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  kind TEXT NOT NULL CHECK (kind IN ('food','training','health_report','daily_tip')),
  title TEXT,
  payload JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pet_plans TO authenticated;
GRANT ALL ON public.pet_plans TO service_role;
ALTER TABLE public.pet_plans ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Owners manage own pet plans" ON public.pet_plans FOR ALL
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- updated_at trigger for pets
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END; $$
LANGUAGE plpgsql SET search_path = public;

DROP TRIGGER IF EXISTS update_pets_updated_at ON public.pets;
CREATE TRIGGER update_pets_updated_at BEFORE UPDATE ON public.pets
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Extend signup to grant petia access
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, display_name, avatar_url)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'name', NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)),
    NEW.raw_user_meta_data->>'avatar_url'
  )
  ON CONFLICT (id) DO NOTHING;

  INSERT INTO public.user_roles (user_id, role) VALUES (NEW.id, 'user')
  ON CONFLICT (user_id, role) DO NOTHING;

  INSERT INTO public.app_entitlements (user_id, app_slug, status)
  VALUES
    (NEW.id, 'saboria', 'active'),
    (NEW.id, 'socialia', 'active'),
    (NEW.id, 'petia', 'active')
  ON CONFLICT (user_id, app_slug) DO NOTHING;

  RETURN NEW;
END;
$$;

-- Backfill existing users
INSERT INTO public.app_entitlements (user_id, app_slug, status)
SELECT id, 'petia', 'active' FROM auth.users
ON CONFLICT (user_id, app_slug) DO NOTHING;
